import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import NavBar from "../components/navbar/page";
import Footer from "../components/footer/page";
import Providers from "./providers";
import { GoogleTagManager } from '@next/third-parties/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Textile Trend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <GoogleTagManager gtmId="GTM-WKPLL9WN" />
      <body className={`${inter.className} bg-base-100`}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WKPLL9WN"
          height="0" width="0" style={{display:"none",visibility:"hidden"}}></iframe></noscript>
      </body>
    </html>
  );
}
